version: "3.8"

services:
  uptime-bot:
    build: .
    container_name: uptime_monitoring_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
